// Bank soal games HABI REST API — 100% lokal, tanpa API pihak ketiga.
// Ditulis dari nol untuk HABI AI.

const flag = (code) => `https://flagcdn.com/w320/${code}.png`
const logo = (domain) => `https://logo.clearbit.com/${domain}`

// ---------- a) TEBAK BENDERA ----------
export const tebakbendera = [
  { soal: flag('id'), jawaban: 'Indonesia' },
  { soal: flag('my'), jawaban: 'Malaysia' },
  { soal: flag('us'), jawaban: 'Amerika Serikat' },
  { soal: flag('jp'), jawaban: 'Jepang' },
  { soal: flag('kr'), jawaban: 'Korea Selatan' },
  { soal: flag('gb'), jawaban: 'Inggris' },
  { soal: flag('fr'), jawaban: 'Prancis' },
  { soal: flag('de'), jawaban: 'Jerman' },
  { soal: flag('sa'), jawaban: 'Arab Saudi' },
  { soal: flag('ae'), jawaban: 'Uni Emirat Arab' },
  { soal: flag('qa'), jawaban: 'Qatar' },
  { soal: flag('eg'), jawaban: 'Mesir' },
  { soal: flag('tr'), jawaban: 'Turki' },
  { soal: flag('in'), jawaban: 'India' },
  { soal: flag('cn'), jawaban: 'China' },
  { soal: flag('th'), jawaban: 'Thailand' },
  { soal: flag('vn'), jawaban: 'Vietnam' },
  { soal: flag('ph'), jawaban: 'Filipina' },
  { soal: flag('sg'), jawaban: 'Singapura' },
  { soal: flag('au'), jawaban: 'Australia' },
  { soal: flag('br'), jawaban: 'Brasil' },
  { soal: flag('ar'), jawaban: 'Argentina' },
  { soal: flag('es'), jawaban: 'Spanyol' },
  { soal: flag('it'), jawaban: 'Italia' },
  { soal: flag('nl'), jawaban: 'Belanda' },
  { soal: flag('ru'), jawaban: 'Rusia' },
  { soal: flag('za'), jawaban: 'Afrika Selatan' },
  { soal: flag('ng'), jawaban: 'Nigeria' },
  { soal: flag('mx'), jawaban: 'Meksiko' },
  { soal: flag('ca'), jawaban: 'Kanada' },
]

// ---------- b) TEBAK LOGO ----------
export const tebaklogo = [
  { deskripsi: 'Mesin pencari nomor satu di dunia', img: logo('google.com'), jawaban: 'Google' },
  { deskripsi: 'Logo buah apel yang digigit', img: logo('apple.com'), jawaban: 'Apple' },
  { deskripsi: 'Raksasa elektronik asal Korea Selatan', img: logo('samsung.com'), jawaban: 'Samsung' },
  { deskripsi: 'Merek mobil asal Jepang', img: logo('toyota.com'), jawaban: 'Toyota' },
  { deskripsi: 'Restoran cepat saji dengan logo huruf M kuning', img: logo('mcdonalds.com'), jawaban: 'McDonalds' },
  { deskripsi: 'Kedai kopi dengan logo putri duyung hijau', img: logo('starbucks.com'), jawaban: 'Starbucks' },
  { deskripsi: 'Merek olahraga dengan logo centang (swoosh)', img: logo('nike.com'), jawaban: 'Nike' },
  { deskripsi: 'Merek olahraga dengan logo tiga garis', img: logo('adidas.com'), jawaban: 'Adidas' },
  { deskripsi: 'Minuman soda legendaris berwarna merah', img: logo('coca-cola.com'), jawaban: 'Coca Cola' },
  { deskripsi: 'Minuman soda saingan berat Coca Cola', img: logo('pepsi.com'), jawaban: 'Pepsi' },
  { deskripsi: 'Raksasa software pembuat Windows', img: logo('microsoft.com'), jawaban: 'Microsoft' },
  { deskripsi: 'Media sosial dengan logo huruf f', img: logo('facebook.com'), jawaban: 'Facebook' },
  { deskripsi: 'Media sosial foto dengan logo kamera', img: logo('instagram.com'), jawaban: 'Instagram' },
  { deskripsi: 'Aplikasi video pendek yang viral', img: logo('tiktok.com'), jawaban: 'TikTok' },
  { deskripsi: 'Platform video terbesar di dunia', img: logo('youtube.com'), jawaban: 'YouTube' },
  { deskripsi: 'Layanan streaming film dengan logo huruf N merah', img: logo('netflix.com'), jawaban: 'Netflix' },
  { deskripsi: 'E-commerce dengan logo tas belanja oranye', img: logo('shopee.com'), jawaban: 'Shopee' },
  { deskripsi: 'E-commerce hijau kebanggaan Indonesia', img: logo('tokopedia.com'), jawaban: 'Tokopedia' },
  { deskripsi: 'Ojek online dengan logo hijau', img: logo('gojek.com'), jawaban: 'Gojek' },
  { deskripsi: 'Minimarket biru kuning di tiap sudut jalan', img: logo('indomaret.co.id'), jawaban: 'Indomaret' },
  { deskripsi: 'Aplikasi chat dengan logo telepon hijau', img: logo('whatsapp.com'), jawaban: 'WhatsApp' },
  { deskripsi: 'Aplikasi chat dengan logo pesawat kertas biru', img: logo('telegram.org'), jawaban: 'Telegram' },
]

// ---------- c) TEBAK LIRIK ----------
export const tebaklirik = [
  { soal: 'Balonku ada lima, rupa-rupa warnanya, hijau _____ dan biru', jawaban: 'kuning' },
  { soal: 'Naik kereta api, tut tut tut, siapa hendak _____', jawaban: 'turut' },
  { soal: 'Cicak-cicak di dinding, _____ merayap', jawaban: 'diam-diam' },
  { soal: 'Potong bebek angsa, masak di _____', jawaban: 'kuali' },
  { soal: 'Kasih ibu kepada beta, tak terhingga _____ masa', jawaban: 'sepanjang' },
  { soal: 'Indonesia _____, tanah tumpah darahku', jawaban: 'tanah airku' },
  { soal: 'Bintang kecil di langit yang biru, amat banyak menghias _____', jawaban: 'angkasa' },
  { soal: 'Topi saya bundar, bundar topi saya, kalau tidak bundar, _____ topi saya', jawaban: 'bukan' },
  { soal: 'Burung kakak tua, hinggap di _____', jawaban: 'jendela' },
  { soal: 'Ambilkan bulan bu, ambilkan bulan bu yang selalu _____ di langit', jawaban: 'bersinar' },
  { soal: 'Lihat kebunku penuh dengan bunga, ada yang putih dan ada yang _____', jawaban: 'merah' },
  { soal: 'Kelinciku, kelinciku, kau manis _____', jawaban: 'sekali' },
  { soal: 'Desaku yang kucinta, pujaan _____', jawaban: 'hatiku' },
  { soal: 'Mimpi adalah _____ untuk kita menaklukkan dunia (Nidji - Laskar Pelangi)', jawaban: 'kunci' },
  { soal: 'Karena aku manusia _____ (Fourtwnty - Mangu)', jawaban: 'biasa' },
  { soal: 'Pergilah kasih, kejarlah keinginanmu, selagi masih _____ waktumu (Chrisye)', jawaban: 'ada' },
  { soal: 'Aku cinta dia, aku sayang dia, _____ juga dia (Chrisye)', jawaban: 'rindu' },
  { soal: 'Kau begitu _____, di mataku kau begitu indah (Andra & The Backbone)', jawaban: 'sempurna' },
  { soal: 'Seperti bintang di surga, dan seluruh warna, dan kasih yang _____ (Peterpan)', jawaban: 'setia' },
  { soal: 'Ning stasiun balapan, kuto Solo sing dadi _____ (Didi Kempot)', jawaban: 'kenangan' },
  { soal: 'Aku ra lilo yen kowe dikawin wong _____ (Didi Kempot - Pamer Bojo)', jawaban: 'liyo' },
  { soal: 'Kudune kowe ngerti, _____ tenan rasane (Gildcoustic - Nemen)', jawaban: 'tresno' },
  { soal: 'Sayang, opo kowe _____, jerite atiku (Via Vallen)', jawaban: 'krungu' },
  { soal: 'Tansah _____, nyanding sliramu (Denny Caknan - Widodari)', jawaban: 'kelingan' },
]

// ---------- d) TEBAK APAKAH AKU ----------
export const tebakapakahaku = [
  { soal: 'Aku punya banyak kunci tapi tak bisa membuka pintu. Apakah aku?', jawaban: 'piano' },
  { soal: 'Semakin banyak diambil, semakin besar aku. Apakah aku?', jawaban: 'lubang' },
  { soal: 'Aku selalu lapar, kalau diberi minum aku mati. Apakah aku?', jawaban: 'api' },
  { soal: 'Aku mengalir tanpa kaki, punya mulut tapi tak bisa bicara. Apakah aku?', jawaban: 'sungai' },
  { soal: 'Aku punya tangan tapi tak bisa memegang, punya wajah tapi tak bisa melihat. Apakah aku?', jawaban: 'jam' },
  { soal: 'Aku bisa terbang tanpa sayap dan menangis tanpa mata. Apakah aku?', jawaban: 'awan' },
  { soal: 'Apa yang selalu naik tapi tak pernah turun?', jawaban: 'umur' },
  { soal: 'Apa yang selalu datang tapi tak pernah tiba?', jawaban: 'besok' },
  { soal: 'Aku punya leher tapi tak punya kepala. Apakah aku?', jawaban: 'botol' },
  { soal: 'Aku punya banyak gigi tapi tak bisa menggigit. Apakah aku?', jawaban: 'sisir' },
  { soal: 'Aku punya kota tapi tak punya rumah, punya gunung tapi tak punya pohon. Apakah aku?', jawaban: 'peta' },
  { soal: 'Aku keliling dunia tapi selalu diam di sudut. Apakah aku?', jawaban: 'perangko' },
  { soal: 'Aku punya satu mata tapi tak bisa melihat. Apakah aku?', jawaban: 'jarum' },
  { soal: 'Aku membuatmu kering tapi aku sendiri basah. Apakah aku?', jawaban: 'handuk' },
  { soal: 'Dibuang kulitnya, dimasak isinya, dimakan kulitnya, dibuang isinya. Apakah itu?', jawaban: 'jagung' },
  { soal: 'Aku selalu mengikutimu tapi tak pernah bisa kau sentuh. Apakah aku?', jawaban: 'bayangan' },
  { soal: 'Semakin tua aku, semakin pendek aku. Apakah aku?', jawaban: 'lilin' },
  { soal: 'Apa yang bisa ditangkap tapi tak bisa dilempar?', jawaban: 'pilek' },
  { soal: 'Aku diawali huruf A dan diakhiri huruf P, padahal aku hanya satu kata. Apakah aku?', jawaban: 'amplop' },
  { soal: 'Aku berbicara tanpa mulut dan mendengar tanpa telinga. Apakah aku?', jawaban: 'gema' },
  { soal: 'Apa yang harus dipecahkan dulu sebelum bisa digunakan?', jawaban: 'telur' },
  { soal: 'Aku ada di mana-mana tapi tak terlihat. Apakah aku?', jawaban: 'udara' },
  { soal: 'Semakin dibagikan, semakin bertambah. Apakah aku?', jawaban: 'ilmu' },
  { soal: 'Aku jatuh dari langit tapi tak pernah terluka. Apakah aku?', jawaban: 'hujan' },
  { soal: 'Saat dibeli aku hitam, saat dipakai aku merah, saat dibuang aku abu-abu. Apakah aku?', jawaban: 'arang' },
  { soal: 'Dipegang ekornya, diputar kepalanya. Apakah itu?', jawaban: 'gasing' },
  { soal: 'Masuknya hijau, keluarnya merah, yang berhenti di dalam kuning. Apakah itu?', jawaban: 'semangka' },
  { soal: 'Kalau hitam dibilang bersih, kalau putih dibilang kotor. Apakah aku?', jawaban: 'papan tulis' },
  { soal: 'Aku selalu naik ke atas dan tak pernah turun. Apakah aku?', jawaban: 'asap' },
  { soal: 'Aku dipukul tapi malah tertawa. Apakah aku?', jawaban: 'bedug' },
  { soal: 'Aku punya banyak lubang tapi bisa menampung air. Apakah aku?', jawaban: 'spons' },
  { soal: 'Aku bisa mengisi ruangan tapi tak memakan tempat. Apakah aku?', jawaban: 'cahaya' },
]

// ---------- e) TEBAK KATA ----------
export const tebakkata = [
  { soal: 'UKUB', jawaban: 'buku' },
  { soal: 'AJEM', jawaban: 'meja' },
  { soal: 'SIKUR', jawaban: 'kursi' },
  { soal: 'HASELOK', jawaban: 'sekolah' },
  { soal: 'LIPENS', jawaban: 'pensil' },
  { soal: 'NGABU', jawaban: 'bunga' },
  { soal: 'NOPOH', jawaban: 'pohon' },
  { soal: 'RITAHAAM', jawaban: 'matahari' },
  { soal: 'NABUL', jawaban: 'bulan' },
  { soal: 'GINTANB', jawaban: 'bintang' },
  { soal: 'TULA', jawaban: 'laut' },
  { soal: 'NUNGGU', jawaban: 'gunung' },
  { soal: 'TAHUN', jawaban: 'hutan' },
  { soal: 'NGAISU', jawaban: 'sungai' },
  { soal: 'CINGKU', jawaban: 'kucing' },
  { soal: 'JINGAN', jawaban: 'anjing' },
  { soal: 'RUNGBU', jawaban: 'burung' },
  { soal: 'NAKI', jawaban: 'ikan' },
  { soal: 'KANAMAN', jawaban: 'makanan' },
  { soal: 'NAMINUM', jawaban: 'minuman' },
  { soal: 'HAMUR', jawaban: 'rumah' },
  { soal: 'LAJENDE', jawaban: 'jendela' },
  { soal: 'TUNIP', jawaban: 'pintu' },
  { soal: 'MARKA', jawaban: 'kamar' },
  { soal: 'RUPAD', jawaban: 'dapur' },
  { soal: 'VISITELE', jawaban: 'televisi' },
  { soal: 'NEPHOHAND', jawaban: 'handphone' },
  { soal: 'DAPESE', jawaban: 'sepeda' },
  { soal: 'LIMOB', jawaban: 'mobil' },
  { soal: 'WATAPES', jawaban: 'pesawat' },
]

// ---------- f) CAK LONTONG ----------
export const caklontong = [
  { soal: 'Apa bedanya gajah dan semut?', jawaban: 'Gajah bisa kesemutan, semut tidak bisa kegajahan', keterangan: 'Gajah bisa kena semut (kesemutan), tapi semut tidak bisa kena gajah.' },
  { soal: 'Apa bedanya sepatu dan jengkol?', jawaban: 'Kalau sepatu disemir, kalau jengkol disemur', keterangan: 'Sama-sama di-semir, beda nasib di dapur.' },
  { soal: 'Hewan apa yang bersaudara?', jawaban: 'Katak-beradik', keterangan: 'Katak + kakak beradik = katak-beradik.' },
  { soal: 'Hewan apa yang paling aneh?', jawaban: 'Belalang kupu-kupu', keterangan: 'Siang makan nasi, malam minum susu. Belalang kok kupu-kupu?' },
  { soal: 'Buah apa yang durhaka?', jawaban: 'Melon-kundang', keterangan: 'Malin Kundang yang dikutuk jadi batu, ini versi buahnya.' },
  { soal: 'Sayur apa yang bisa nyanyi?', jawaban: 'Kol-play', keterangan: 'Kol + Coldplay, band kesukaan para sayur.' },
  { soal: 'Sayur apa yang dingin?', jawaban: 'Kembang kol', keterangan: 'Kol = cold, bahasa Inggrisnya dingin.' },
  { soal: 'Buah apa yang paling kaya?', jawaban: 'Srikaya', keterangan: 'Sri artinya kaya. Jadi buahnya kaya raya.' },
  { soal: 'Ikan apa yang hidup di darat?', jawaban: 'Ikan asin', keterangan: 'Habis digoreng, tinggalnya di piring di darat.' },
  { soal: 'Ikan apa yang suka ngeband?', jawaban: 'Ikan band-eng', keterangan: 'Band + bandeng = musisi bawah laut.' },
  { soal: 'Kenapa air laut asin?', jawaban: 'Karena ikannya keringatan', keterangan: 'Air laut asin karena keringat ikan. Masuk akal kan?' },
  { soal: 'Kenapa kucing mengeong?', jawaban: 'Karena kalau menggonggong namanya anjing', keterangan: 'Setiap hewan punya suara khasnya masing-masing.' },
  { soal: 'Kenapa anjing menggonggong?', jawaban: 'Karena kalau mengeong namanya kucing', keterangan: 'Kebalikan dari pertanyaan sebelumnya.' },
  { soal: 'Apa yang selalu di depan kita tapi tidak bisa dilihat?', jawaban: 'Masa depan', keterangan: 'Selalu di depan, tapi tidak pernah terlihat.' },
  { soal: 'Apa yang ada di ujung langit?', jawaban: 'Huruf T', keterangan: 'Langit diakhiri huruf T: langi-T.' },
  { soal: 'Kenapa pohon kelapa tidak berbuah durian?', jawaban: 'Karena namanya pohon kelapa, bukan pohon durian', keterangan: 'Logika sederhana yang tak terbantahkan.' },
  { soal: 'Apa bedanya gajah Afrika dan gajah Asia?', jawaban: 'Gajah Afrika tinggal di Afrika, gajah Asia tinggal di Asia', keterangan: 'Sudah jelas dari namanya.' },
  { soal: 'Kenapa kita harus makan?', jawaban: 'Karena kalau tidak makan, lapar', keterangan: 'Fakta kehidupan yang pahit.' },
  { soal: 'Kenapa orang mandi pakai sabun?', jawaban: 'Karena kalau pakai sambal, pedas', keterangan: 'Mandi pakai sambal = mandi penderitaan.' },
  { soal: 'Kenapa sepeda rodanya dua?', jawaban: 'Karena kalau satu susah seimbang, kalau tiga namanya becak', keterangan: 'Dua itu angka yang pas.' },
  { soal: 'Kenapa kipas angin tidak pernah pusing padahal muter terus?', jawaban: 'Karena dia tidak punya kepala', keterangan: 'Tidak punya kepala = tidak bisa pusing.' },
  { soal: 'Kenapa jam dinding selalu menatap kita?', jawaban: 'Karena dia tidak punya kelopak mata', keterangan: 'Matanya selalu terbuka 24 jam.' },
  { soal: 'Apa bedanya lampu dan matahari?', jawaban: 'Lampu bisa dimatikan, matahari tidak bisa', keterangan: 'Coba matikan matahari kalau bisa.' },
  { soal: 'Kenapa bintang kelihatan kecil?', jawaban: 'Karena jauh. Kalau dekat namanya lampu', keterangan: 'Jarak menentukan ukuran.' },
  { soal: 'Kenapa hujan turun ke bawah?', jawaban: 'Karena kalau ke atas namanya uap', keterangan: 'Hujan turun, uap naik. Sudah kodratnya.' },
  { soal: 'Kenapa pintu diketuk sebelum dibuka?', jawaban: 'Karena kalau dibuka dulu, tidak perlu diketuk', keterangan: 'Urutan yang benar: ketuk dulu, baru buka.' },
]
